from .loader import load_prompt

from .note_integration import (
    TOPIC_NOTE_GENERATION_PROMPT,
    CONTENT_SUMMARIZE_PROMPT,
    CONTENT_COMPRESS_PROMPT,
    DOC_TOPIC_MAPPING_PROMPT
)

from .topic_extraction import (
    TOPIC_EXTRACTION_BY_FILENAMES_PROMPT,
    TOPIC_COUNT_SPECIFIED_INSTRUCTIONS_PROMPT,
    OUTPUT_FORMAT_SPECIFIED_INSTRUCTIONS_PROMPT,
    TOPIC_COUNT_AUTO_INSTRUCTIONS_PROMPT,
    OUTPUT_FORMAT_AUTO_INSTRUCTIONS_PROMPT
)

from .llm_rewrite import (
    LLM_REWRITE_PROMPT
)

from .ai_topic_consolidate import (
    AI_TOPIC_ANALYZE_PROMPT
)

from .topic_survey import (
    TOPIC_SURVEY_PROMPT
)

from .rag_assistant import (
    ASSISTANT_PERSONA_PROMPT,
    HYDE_PROMPT,
    RAG_ASSISTANT_PROMPT,
    RAG_ASSISTANT_WEB_PROMPT,
    RAG_ASSISTANT_NO_CONTEXT_PROMPT,
    MEMORY_COMPRESS_PROMPT,
    LONG_MEMORY_COMPRESS_PROMPT,
    USER_INFO_EXTRACT_PROMPT,
    ASSISTANT_ACTION_PROMPT,
    FILE_OPERATION_PROMPT
)

from .cascade import (
    CASCADE_SURVEY_NEW_PROMPT,
    CASCADE_SURVEY_UPDATE_PROMPT
)

from .profile import (
    PROFILE_EXTRACT_PROMPT,
    PROFILE_INFERENCE_PROMPT,
    PROFILE_SUMMARY_PROMPT
)

from .file_conversion import (
    PDF_TO_MARKDOWN_PROMPT,
    DOCX_TO_MARKDOWN_PROMPT,
    PPTX_TO_MARKDOWN_PROMPT,
    TXT_TO_MARKDOWN_PROMPT,
    MARKDOWN_TO_DOCX_PROMPT,
    CONTENT_CLEANING_PROMPT
)

from .unified import (
    GENERAL_CONTENT_TO_MARKDOWN_PROMPT,
    CLEAN_MARKDOWN_PROMPT,
    FORMAT_OPTIMIZATION_PROMPT,
    MARKDOWN_REFORMAT_PROMPT
)

from .web_download import (
    WEB_TO_MARKDOWN_PROMPT,
)

from .topic_assignment import (
    TOPIC_SUGGESTION_PROMPT
)

from .abstract import (
    ABSTRACT_PROMPT
)

__all__ = [
    'load_prompt',
    'TOPIC_NOTE_GENERATION_PROMPT',
    'CONTENT_SUMMARIZE_PROMPT',
    'CONTENT_COMPRESS_PROMPT',
    'DOC_TOPIC_MAPPING_PROMPT',
    'TOPIC_EXTRACTION_BY_FILENAMES_PROMPT',
    'TOPIC_COUNT_SPECIFIED_INSTRUCTIONS_PROMPT',
    'OUTPUT_FORMAT_SPECIFIED_INSTRUCTIONS_PROMPT',
    'TOPIC_COUNT_AUTO_INSTRUCTIONS_PROMPT',
    'OUTPUT_FORMAT_AUTO_INSTRUCTIONS_PROMPT',
    'LLM_REWRITE_PROMPT',
    'AI_TOPIC_ANALYZE_PROMPT',
    'TOPIC_SURVEY_PROMPT',
    'ASSISTANT_PERSONA_PROMPT',
    'HYDE_PROMPT',
    'RAG_ASSISTANT_PROMPT',
    'RAG_ASSISTANT_WEB_PROMPT',
    'RAG_ASSISTANT_NO_CONTEXT_PROMPT',
    'MEMORY_COMPRESS_PROMPT',
    'LONG_MEMORY_COMPRESS_PROMPT',
    'USER_INFO_EXTRACT_PROMPT',
    'ASSISTANT_ACTION_PROMPT',
    'FILE_OPERATION_PROMPT',
    'CASCADE_SURVEY_NEW_PROMPT',
    'CASCADE_SURVEY_UPDATE_PROMPT',
    'PROFILE_EXTRACT_PROMPT',
    'PROFILE_INFERENCE_PROMPT',
    'PROFILE_SUMMARY_PROMPT',
    'PDF_TO_MARKDOWN_PROMPT',
    'DOCX_TO_MARKDOWN_PROMPT',
    'PPTX_TO_MARKDOWN_PROMPT',
    'TXT_TO_MARKDOWN_PROMPT',
    'MARKDOWN_TO_DOCX_PROMPT',
    'CONTENT_CLEANING_PROMPT',
    'GENERAL_CONTENT_TO_MARKDOWN_PROMPT',
    'CLEAN_MARKDOWN_PROMPT',
    'FORMAT_OPTIMIZATION_PROMPT',
    'MARKDOWN_REFORMAT_PROMPT',
    'WEB_TO_MARKDOWN_PROMPT',
    'TOPIC_SUGGESTION_PROMPT',
    'ABSTRACT_PROMPT',
]
