"""Prompts package — dual-track loading with clear precedence.

Loading priority (resolved by prompts/loader.py):
  1. YAML files (prompts/yaml/*.yaml) — preferred, always used when present
  2. Python constants (prompts/*.py) — fallback, only used when no YAML match

All prompts currently have both YAML and Python versions.
At runtime, the YAML version takes precedence; the Python constant serves as
a backup and editable reference. Edits to Python constants will NOT take effect
if a corresponding YAML key exists.

To add a new prompt:
  - Add the key to the appropriate YAML file in prompts/yaml/
  - Optionally mirror it as a Python constant in the matching prompts/*.py module
"""

from .loader import load_prompt, get_prompt

ASSISTANT_READONLY_PROMPT = get_prompt("agent", "ASSISTANT_READONLY_PROMPT")
AGENT_SYSTEM_PROMPT = get_prompt("agent", "AGENT_SYSTEM_PROMPT")
AGENT_TOOL_RESULT_PROMPT = get_prompt("agent", "AGENT_TOOL_RESULT_PROMPT")
ASSISTANT_READONLY_TOOL_RESULT_PROMPT = get_prompt("agent", "ASSISTANT_READONLY_TOOL_RESULT_PROMPT")

TOPIC_NOTE_GENERATION_PROMPT = get_prompt("note_integration", "TOPIC_NOTE_GENERATION_PROMPT")
CONTENT_SUMMARIZE_PROMPT = get_prompt("note_integration", "CONTENT_SUMMARIZE_PROMPT")
CONTENT_COMPRESS_PROMPT = get_prompt("note_integration", "CONTENT_COMPRESS_PROMPT")
DOC_TOPIC_MAPPING_PROMPT = get_prompt("note_integration", "DOC_TOPIC_MAPPING_PROMPT")
INGEST_NOTE_COMPILE_PROMPT = get_prompt("note_compile", "INGEST_NOTE_COMPILE_PROMPT")

TOPIC_EXTRACTION_BY_FILENAMES_PROMPT = get_prompt("topic_extraction", "TOPIC_EXTRACTION_BY_FILENAMES_PROMPT")
TOPIC_COUNT_SPECIFIED_INSTRUCTIONS_PROMPT = get_prompt("topic_extraction", "TOPIC_COUNT_SPECIFIED_INSTRUCTIONS_PROMPT")
OUTPUT_FORMAT_SPECIFIED_INSTRUCTIONS_PROMPT = get_prompt("topic_extraction", "OUTPUT_FORMAT_SPECIFIED_INSTRUCTIONS_PROMPT")
TOPIC_COUNT_AUTO_INSTRUCTIONS_PROMPT = get_prompt("topic_extraction", "TOPIC_COUNT_AUTO_INSTRUCTIONS_PROMPT")
OUTPUT_FORMAT_AUTO_INSTRUCTIONS_PROMPT = get_prompt("topic_extraction", "OUTPUT_FORMAT_AUTO_INSTRUCTIONS_PROMPT")

LLM_REWRITE_PROMPT = get_prompt("llm_rewrite", "LLM_REWRITE_PROMPT")

AI_TOPIC_ANALYZE_PROMPT = get_prompt("ai_topic_consolidate", "AI_TOPIC_ANALYZE_PROMPT")

TOPIC_SURVEY_PROMPT = get_prompt("topic_survey", "TOPIC_SURVEY_PROMPT")

ASSISTANT_PERSONA_PROMPT = get_prompt("rag_assistant", "ASSISTANT_PERSONA_PROMPT")
HYDE_PROMPT = get_prompt("rag_assistant", "HYDE_PROMPT")
RAG_ASSISTANT_PROMPT = get_prompt("rag_assistant", "RAG_ASSISTANT_PROMPT")
RAG_ASSISTANT_WEB_PROMPT = get_prompt("rag_assistant", "RAG_ASSISTANT_WEB_PROMPT")
RAG_ASSISTANT_NO_CONTEXT_PROMPT = get_prompt("rag_assistant", "RAG_ASSISTANT_NO_CONTEXT_PROMPT")
RAG_CHAT_PROMPT = get_prompt("rag_assistant", "RAG_CHAT_PROMPT")
RAG_HYDE_PROMPT = get_prompt("rag_assistant", "RAG_HYDE_PROMPT")
MEMORY_COMPRESS_PROMPT = get_prompt("rag_assistant", "MEMORY_COMPRESS_PROMPT")
LONG_MEMORY_COMPRESS_PROMPT = get_prompt("rag_assistant", "LONG_MEMORY_COMPRESS_PROMPT")
USER_INFO_EXTRACT_PROMPT = get_prompt("rag_assistant", "USER_INFO_EXTRACT_PROMPT")
ASSISTANT_ACTION_PROMPT = get_prompt("rag_assistant", "ASSISTANT_ACTION_PROMPT")
FILE_OPERATION_PROMPT = get_prompt("rag_assistant", "FILE_OPERATION_PROMPT")

CASCADE_SURVEY_NEW_PROMPT = get_prompt("cascade", "CASCADE_SURVEY_NEW_PROMPT")
CASCADE_SURVEY_UPDATE_PROMPT = get_prompt("cascade", "CASCADE_SURVEY_UPDATE_PROMPT")
SURVEY_CHAT_APPEND_PROMPT = get_prompt("cascade", "SURVEY_CHAT_APPEND_PROMPT")

PROFILE_EXTRACT_PROMPT = get_prompt("profile", "PROFILE_EXTRACT_PROMPT")
PROFILE_INFERENCE_PROMPT = get_prompt("profile", "PROFILE_INFERENCE_PROMPT")
PROFILE_SUMMARY_PROMPT = get_prompt("profile", "PROFILE_SUMMARY_PROMPT")

PDF_TO_MARKDOWN_PROMPT = get_prompt("file_conversion", "PDF_TO_MARKDOWN_PROMPT")
DOCX_TO_MARKDOWN_PROMPT = get_prompt("file_conversion", "DOCX_TO_MARKDOWN_PROMPT")
PPTX_TO_MARKDOWN_PROMPT = get_prompt("file_conversion", "PPTX_TO_MARKDOWN_PROMPT")
TXT_TO_MARKDOWN_PROMPT = get_prompt("file_conversion", "TXT_TO_MARKDOWN_PROMPT")
MARKDOWN_TO_DOCX_PROMPT = get_prompt("file_conversion", "MARKDOWN_TO_DOCX_PROMPT")
CONTENT_CLEANING_PROMPT = get_prompt("file_conversion", "CONTENT_CLEANING_PROMPT")

GENERAL_CONTENT_TO_MARKDOWN_PROMPT = get_prompt("unified", "GENERAL_CONTENT_TO_MARKDOWN_PROMPT")
CLEAN_MARKDOWN_PROMPT = get_prompt("unified", "CLEAN_MARKDOWN_PROMPT")
FORMAT_OPTIMIZATION_PROMPT = get_prompt("unified", "FORMAT_OPTIMIZATION_PROMPT")
MARKDOWN_REFORMAT_PROMPT = get_prompt("unified", "MARKDOWN_REFORMAT_PROMPT")

WEB_TO_MARKDOWN_PROMPT = get_prompt("web_download", "WEB_TO_MARKDOWN_PROMPT")

TOPIC_SUGGESTION_PROMPT = get_prompt("topic_assignment", "TOPIC_SUGGESTION_PROMPT")

ABSTRACT_PROMPT = get_prompt("abstract", "ABSTRACT_PROMPT")

CLOUD_SYNC_CONFLICT_NOTICE_PROMPT = get_prompt("cloud_sync", "CLOUD_SYNC_CONFLICT_NOTICE_PROMPT")
CLOUD_SYNC_PUSH_SUMMARY_PROMPT = get_prompt("cloud_sync", "CLOUD_SYNC_PUSH_SUMMARY_PROMPT")
CLOUD_SYNC_PULL_SUMMARY_PROMPT = get_prompt("cloud_sync", "CLOUD_SYNC_PULL_SUMMARY_PROMPT")

__all__ = [
    'load_prompt',
    'get_prompt',
    'ASSISTANT_READONLY_PROMPT',
    'AGENT_SYSTEM_PROMPT',
    'AGENT_TOOL_RESULT_PROMPT',
    'ASSISTANT_READONLY_TOOL_RESULT_PROMPT',
    'TOPIC_NOTE_GENERATION_PROMPT',
    'CONTENT_SUMMARIZE_PROMPT',
    'CONTENT_COMPRESS_PROMPT',
    'DOC_TOPIC_MAPPING_PROMPT',
    'INGEST_NOTE_COMPILE_PROMPT',
    'TOPIC_EXTRACTION_BY_FILENAMES_PROMPT',
    'TOPIC_COUNT_SPECIFIED_INSTRUCTIONS_PROMPT',
    'OUTPUT_FORMAT_SPECIFIED_INSTRUCTIONS_PROMPT',
    'TOPIC_COUNT_AUTO_INSTRUCTIONS_PROMPT',
    'OUTPUT_FORMAT_AUTO_INSTRUCTIONS_PROMPT',
    'LLM_REWRITE_PROMPT',
    'AI_TOPIC_ANALYZE_PROMPT',
    'TOPIC_SURVEY_PROMPT',
    'ASSISTANT_PERSONA_PROMPT',
    'HYDE_PROMPT',
    'RAG_ASSISTANT_PROMPT',
    'RAG_ASSISTANT_WEB_PROMPT',
    'RAG_ASSISTANT_NO_CONTEXT_PROMPT',
    'RAG_CHAT_PROMPT',
    'RAG_HYDE_PROMPT',
    'MEMORY_COMPRESS_PROMPT',
    'LONG_MEMORY_COMPRESS_PROMPT',
    'USER_INFO_EXTRACT_PROMPT',
    'ASSISTANT_ACTION_PROMPT',
    'FILE_OPERATION_PROMPT',
    'CASCADE_SURVEY_NEW_PROMPT',
    'CASCADE_SURVEY_UPDATE_PROMPT',
    'SURVEY_CHAT_APPEND_PROMPT',
    'PROFILE_EXTRACT_PROMPT',
    'PROFILE_INFERENCE_PROMPT',
    'PROFILE_SUMMARY_PROMPT',
    'PDF_TO_MARKDOWN_PROMPT',
    'DOCX_TO_MARKDOWN_PROMPT',
    'PPTX_TO_MARKDOWN_PROMPT',
    'TXT_TO_MARKDOWN_PROMPT',
    'MARKDOWN_TO_DOCX_PROMPT',
    'CONTENT_CLEANING_PROMPT',
    'GENERAL_CONTENT_TO_MARKDOWN_PROMPT',
    'CLEAN_MARKDOWN_PROMPT',
    'FORMAT_OPTIMIZATION_PROMPT',
    'MARKDOWN_REFORMAT_PROMPT',
    'WEB_TO_MARKDOWN_PROMPT',
    'TOPIC_SUGGESTION_PROMPT',
    'ABSTRACT_PROMPT',
    'CLOUD_SYNC_CONFLICT_NOTICE_PROMPT',
    'CLOUD_SYNC_PUSH_SUMMARY_PROMPT',
    'CLOUD_SYNC_PULL_SUMMARY_PROMPT',
]
