from .web_download import (
    WEB_TO_MARKDOWN_PROMPT,
    CLEAN_MARKDOWN_PROMPT as WEB_CLEAN_MARKDOWN_PROMPT,
    FORMAT_OPTIMIZATION_PROMPT as WEB_FORMAT_OPTIMIZATION_PROMPT
)

from .file_conversion import (
    PDF_TO_MARKDOWN_PROMPT,
    DOCX_TO_MARKDOWN_PROMPT,
    PPTX_TO_MARKDOWN_PROMPT,
    TXT_TO_MARKDOWN_PROMPT,
    MARKDOWN_TO_DOCX_PROMPT,
    CONTENT_CLEANING_PROMPT
)

from .note_integration import (
    TOPIC_NOTE_GENERATION_PROMPT,
    CONTENT_SUMMARIZE_PROMPT,
    CONTENT_COMPRESS_PROMPT,
    DOC_TOPIC_MAPPING_PROMPT
)

from .topic_extraction import (
    TOPIC_EXTRACTION_BY_FILENAMES_PROMPT,
    TOPIC_COUNT_SPECIFIED_INSTRUCTIONS,
    OUTPUT_FORMAT_SPECIFIED_INSTRUCTIONS,
    TOPIC_COUNT_AUTO_INSTRUCTIONS,
    OUTPUT_FORMAT_AUTO_INSTRUCTIONS
)

from .topic_assignment import (
    TOPIC_SUGGESTION_PROMPT
)

from .unified import (
    GENERAL_CONTENT_TO_MARKDOWN_PROMPT,
    CLEAN_MARKDOWN_PROMPT,
    FORMAT_OPTIMIZATION_PROMPT,
    MARKDOWN_REFORMAT_PROMPT
)

__all__ = [
    # web
    'WEB_TO_MARKDOWN_PROMPT',
    'WEB_CLEAN_MARKDOWN_PROMPT',
    'WEB_FORMAT_OPTIMIZATION_PROMPT',
    # file conversion
    'PDF_TO_MARKDOWN_PROMPT',
    'DOCX_TO_MARKDOWN_PROMPT',
    'PPTX_TO_MARKDOWN_PROMPT',
    'TXT_TO_MARKDOWN_PROMPT',
    'MARKDOWN_TO_DOCX_PROMPT',
    'CONTENT_CLEANING_PROMPT',
    # note integration
    'TOPIC_NOTE_GENERATION_PROMPT',
    'CONTENT_SUMMARIZE_PROMPT',
    'CONTENT_COMPRESS_PROMPT',
    'DOC_TOPIC_MAPPING_PROMPT',
    # topic extraction
    'TOPIC_EXTRACTION_BY_FILENAMES_PROMPT',
    'TOPIC_COUNT_SPECIFIED_INSTRUCTIONS',
    'OUTPUT_FORMAT_SPECIFIED_INSTRUCTIONS',
    'TOPIC_COUNT_AUTO_INSTRUCTIONS',
    'OUTPUT_FORMAT_AUTO_INSTRUCTIONS',
    # topic assignment
    'TOPIC_SUGGESTION_PROMPT',
    # unified
    'GENERAL_CONTENT_TO_MARKDOWN_PROMPT',
    'CLEAN_MARKDOWN_PROMPT',
    'FORMAT_OPTIMIZATION_PROMPT',
    'MARKDOWN_REFORMAT_PROMPT',
]
