[package]
name = "noteai"
version = "1.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt", "sync", "io-util", "process", "time"] }
which = "7"
uuid = { version = "1", features = ["v4"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[features]
default = ["devtools"]
devtools = ["tauri/devtools"]

[lib]
name = "noteai_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
